server:
  port: 9001

spring:
  jpa:
    show-sql: true
  #Configurations H2
  h2:
    console:
      enabled: true
  #défini l'encodage pour data.sql
  datasource:
    sql-script-encoding: UTF-8
    
mes-configs:
  limitDeProduits: 5
