spring:
  jpa:
    show-sql: true

  #Configurations H2
  h2:
    console:
      enabled: true

  #défini l'encodage pour data.sql
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
      
  instance:
    health-check-url-path: /actuator/health

#mes configs
mes-configs:
  limitDeProduits: 6
