server:
  port: 9103

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
  instance:
    health-check-url-path: /actuator/health

spring:
  security:
    user:
      name: utilisateur
      password: mdp
